[workspace.package]
version = "0.22.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/guinea-rs/guinea-plugins"

[workspace]
resolver = "2"
members = ["plugins/*", "widgets"]

[workspace.dependencies]
guinea = { version = "0.22.0", default-features = false }
guinea-core = "0.22.0"
guinea-mark = "0.22.0"

windows-reactor = { package = "windows-reactor-pre", version = "0.101.0" }
windows-canvas = { package = "windows-canvas-pre", version = "0.101.0" }
windows-core = "0.100.0"

anyhow = "1.0.100"
tracing = "0.1.44"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[profile.dev]
debug = 1
incremental = true

[profile.dev.package."*"]
debug = 0
