name: ci

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"

jobs:
  windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: toolchain
        run: |
          rustup toolchain install
          rustup component add clippy

      - name: capnp
        run: choco install capnproto --no-progress -y

      - name: plugins
        run: |
          cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
          cargo clippy --workspace --all-targets --locked -- -D warnings
          cargo test --workspace --all-features --locked

      - name: devtools
        working-directory: tools/devtools
        run: |
          cargo clippy --workspace --all-targets --locked -- -D warnings
          cargo test --workspace --locked

  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: toolchain
        run: |
          rustup toolchain install
          rustup component add clippy rustfmt

      - name: capnp
        run: sudo apt-get install -y --no-install-recommends capnproto

      - name: plugins
        run: |
          cargo fmt --check
          cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
          cargo clippy --workspace --all-targets --locked -- -D warnings
          cargo test --workspace --all-features --locked

      - name: devtools
        working-directory: tools/devtools
        run: |
          cargo clippy --workspace --all-targets --locked -- -D warnings
          cargo test --workspace --locked
